# DigitalOcean App Platform Configuration
name: seo-booster-ai

services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/seo-booster-ai
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    run_command: npm run docker-start
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: SHOPIFY_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SHOPIFY_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SCOPES
        value: read_products,write_products,read_content,write_content,read_themes,write_themes,read_metaobjects,write_metaobjects,read_files,write_files
      - key: SHOPIFY_APP_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /

databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1
